config/routes.rb
Rails.application.routes.draw do
  resources :contracts
  get 'dashboard/index'
  post 'dashboard/create_form'
  root "dashboard#index"

  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users do
    collection do
      get 'select2'
    end
  end

  resources :passengers do
    collection do
      get 'select2'
      get 'get_passenger_by_identification'
    end
  end

  resources :blood_types do
    collection do
      get 'select2'
    end
  end

  resources :card_types do
    collection do
      get 'select2'
    end
  end
end

app/views/partials/_breadcrumbs.html.erb
<!-- Breadcrumbs-->
<div class="title_right" style="text-align: right;">
  <ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => " / " %>
  </ol>
</div>

app/views/partials/_errorscontent.html.erb
<% if object && object.errors.any? %>
<div class="alert alert-danger">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/partials/_flashcontent.html.erb
<% flash.each do |key, value| %>
  <div id="flash" class="alert alert-<%= key %>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= value %>
  </div>
<% end %>

app/views/partials/_footcontent.html.erb
    </div>
    <!-- /.container-fluid -->
    <%= render "partials/stickyfooter" %>
  </div>
  <!-- /#content-wrapper -->
</div>
<!-- /#wrapper -->

app/views/partials/_headcontent.html.erb
<%= render "partials/headnav" %>
<!-- #wrapper -->
<div id="wrapper">
  <%= render "partials/sidenav" %>
  <!-- #content-wrapper -->
  <div id="content-wrapper">
    <%= render "partials/flashcontent" %>
    <!-- .container-fluid -->
    <div class="container-fluid">
      <%= render "partials/breadcrumbs" %>

app/views/partials/_headnav.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">
  <%= link_to root_path, class: "navbar-brand mr-1" do %>
    <i class="fas fa-fw fa-truck"></i>
    <span>Car Rental</span>
  <% end %>
  <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
    <i class="fas fa-bars"></i>
  </button>
  <ul class="navbar-nav ml-auto mr-0 mr-md-3 my-2 my-md-0">
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user-circle fa-fw"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#">Settings</a>
        <a class="dropdown-item" href="#">Activity Log</a>
        <div class="dropdown-divider"></div>
        <%= link_to destroy_user_session_path, :method => :delete, class: "dropdown-item" do %>
          <i class="fa fa-sign-out pull-right"></i><%= t("gui.actions.logout") %>
        <% end %>
      </div>
    </li>
  </ul>
</nav>

app/views/partials/_sidenav.html.erb
<!-- Sidebar -->
<ul class="sidebar navbar-nav">
  <li class="nav-item">
    <%= link_to root_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-home"></i>
      <span><%= t("gui.menu.dashboard") %></span>
    <% end %>
  </li>
  <% if can? :read, CardType %>
    <li class="nav-item">
      <%= link_to card_types_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-info-circle"></i>
        <span><%= t("activerecord.models.card_type", count: 2) %></span>
      <% end %>
    </li>
  <% end %>
  <% if can? :read, BloodType %>
    <li class="nav-item">
      <%= link_to blood_types_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-info-circle"></i>
        <span><%= t("activerecord.models.blood_type", count: 2) %></span>
      <% end %>
    </li>
  <% end %>
  <% if can? :read, Passenger %>
    <li class="nav-item">
      <%= link_to passengers_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-info-circle"></i>
        <span><%= t("activerecord.models.passenger", count: 2) %></span>
      <% end %>
    </li>
  <% end %>
  <% if can? :read, Contract %>
    <li class="nav-item">
      <%= link_to contracts_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-info-circle"></i>
        <span><%= t("activerecord.models.contract", count: 2) %></span>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/partials/_stickyfooter.html.erb
<hr>
<!-- Sticky Footer -->
<footer class="sticky-footer">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright © Your Website 2019</span>
    </div>
  </div>
</footer>